### ISSUE TITLE
"C:\Program Files (x86)" hardcoded

### ISSUE THREAD

**Issue by abrca** [WildGums/Orc.CommandLine#156]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] .NET Standard
 - [x] .NET Core

## Component

cake scripts

## Version of Library
4.0.0

## Version of OS(s) listed above with issue
Windows

## Steps to Reproduce
see below

## Expected Behavior
see below

## Actual Behavior

This issue most likely affects all orc.* 4.0.0 repositories, so I make an issue not a PR

in files deployment/cake/installers-msix.cake and deployment/cake/lib-generic.cake in 4.0.0 branch
in lines
`var directories = BuildContext.CakeContext.GetDirectories($@"C:/Program Files (x86)/Windows Kits/10/bin/10.0.*");`

"C:/Program Files (x86)/" is a constant string. But this folder have different names in other languages (https://www.samlogic.net/articles/program-files-folder-different-languages.htm)

It's better to use Environment.SpecialFolder.ProgramFilesX86
or some other way to find SDK (https://stackoverflow.com/questions/35119223/how-to-programmatically-detect-and-locate-the-windows-10-sdk)

**Comment by GeertvanHorrik** [comment]
Great comment. Will fix and run repo sync on all repositories.

**Comment by GeertvanHorrik** [comment]
See https://github.com/GeertvanHorrik/RepositoryTemplate/commit/32ee25c80cda0d156d64297f1ec09fef8a885a43
